apiVersion: v1
kind: Service
metadata:
  name: hello-winter
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  selector:
    io.kompose.service: hello-winter
status:
  loadBalancer: {}
